In [3]:
import os
import pandas as pd
import numpy as np
def convert_npy_to_csv(folder_path):
    # Get a list of all files in the specified folder
    files = os.listdir(folder_path)

    # Iterate through each file in the folder
    for file_name in files:
        # Check if the file has a .mat extension
        if file_name.endswith('.npy'):
            # Construct the full path for the .mat file
            npy_file_path = os.path.join(folder_path, file_name)

            # Load data from the .npy file
            npy_data = np.load(npy_file_path)
            #print(npy_data)
            
            # converting each .npy file to .csv
            # accessing the last key of a dictionary which is the form of array
            #last_key = list(npy_data.keys())[-1]
            
            # accessing the array of the last key
            # converting the array in to python standard array form which is dataframe
            df=pd.DataFrame(npy_data)
            print(df)

            # assigning aname for each .csv to be created by removing the last four characters from the original name 
            # and adding .csv 
            file_name = file_name[:-4]+'.csv'
            
            # locating the output folde
            output_file_path = os.path.join(folder_path, file_name)
            
            #writing the array to csv file 
            df.to_csv(output_file_path, index=False)
            #df.to_csv(file_name)
            
folder_path = 'C:/Users/Ewunetie/OneDrive - University of Gondar,/2022-2023 files/Courses/Project/data/Online data/4 ECG Lead 2 Dataset PhysioNet (Open Access)/db_npy/svdb_npy'
convert_npy_to_csv(folder_path)

           0  1
0        162  N
1        330  N
2        497  N
3        666  N
4        836  N
...      ... ..
1878  229735  N
1879  229874  N
1880  230014  N
1881  230153  N
1882  230292  N

[1883 rows x 2 columns]
         0  1
0    39008  ~
1    39584  ~
2    42528  ~
3    44053  |
4    44253  |
5    44352  ~
6    44640  ~
7    45193  ~
8    46240  ~
9    46865  ~
10   52160  ~
11   52431  |
12   52704  ~
13   53728  ~
14   55722  ~
15   65236  |
16   75012  |
17  102109  |
18  183604  |
19  189984  ~
20  191296  ~
21  195213  ~
22  195872  ~
23  213792  ~
24  214336  ~
25  215116  ~
26  215459  ~
27  215511  |
28  215715  |
29  216032  ~
30  216256  ~
31  217248  ~
32  217956  |
33  218976  ~
34  219488  ~
35  221934  ~
36  223424  ~
37  223968  ~
            0
0      -0.505
1      -0.495
2      -0.545
3      -0.445
4      -0.275
...       ...
230395 -0.020
230396  0.000
230397  0.010
230398 -0.020
230399 -0.030

[230400 rows x 1 columns]
           0  1
0         46  N
1        112  V
2        197  N
3        268  V
4        354  N
...      ... ..
2504  229957  N
2505  230050  N
2506  230144  N
2507  230238  N
2508  230333  N

[2509 rows x 2 columns]
         0  1
0        0  "
1     8708  ~
2     9257  ~
3     9889  ~
4    10460  ~
..     ... ..
64  221153  ~
65  225088  ~
66  225714  ~
67  227860  ~
68  228384  ~

[69 rows x 2 columns]
            0
0       0.485
1       0.360
2       0.510
3       0.300
4       0.310
...       ...
230395  0.550
230396  0.470
230397  0.380
230398  0.480
230399  0.570

[230400 rows x 1 columns]
           0  1
0        105  N
1        234  N
2        362  N
3        490  N
4        619  N
...      ... ..
1666  229690  N
1667  229859  N
1668  230036  N
1669  230214  N
1670  230382  N

[1671 rows x 2 columns]
       0  1
0  42009  |
1  42034  |
2  43008  ~
3  43224  |
4  43310  |
5  43590  ~
6  56000  ~
7  56608  ~
                   0
0       6.000000e-02
1       7.000000e-02
2       1.100000e-01
3       1.000000e-01
4       1.400000e-01
...              ...
230395 -2.000000e-02
230396 -2.000000e-02
230397  2.589534e-17
230398  1.215818e-16
230399 -5.000000e-02

[230400 rows x 1 columns]
           0  1
0         95  N
1        207  N
2        318  N
3        433  N
4        545  N
...      ... ..
2063  229812  N
2064  229932  N
2065  230050  N
2066  230168  N
2067  230288  N

[2068 rows x 2 columns]
        0  1
0  199048  ~
1  199478  |
2  199808  ~
            0
0      -0.065
1      -0.055
2      -0.055
3      -0.045
4      -0.035
...       ...
230395 -0.090
230396 -0.110
230397 -0.120
230398 -0.130
230399 -0.120

[230400 rows x 1 columns]
           0  1
0         35  N
1        116  N
2        197  N
3        287  N
4        393  N
...      ... ..
2829  230032  V
2830  230106  N
2831  230196  N
2832  230279  N
2833  230359  N

[2834 rows x 2 columns]
         0  1
0    80928  ~
1    81568  ~
2   108700  ~
3   109472  ~
4   112655  ~
5   113216  ~
6   134400  ~
7   134976  ~
8   135808  ~
9   136352  ~
10  137126  ~
11  138432  ~
12  139648  ~
13  140192  ~
14  142496  ~
15  143968  ~
16  145952  ~
17  146784  ~
18  147214  |
19  148352  ~
20  149088  ~
21  149600  ~
22  150176  ~
23  153632  ~
24  155744  ~
25  171872  ~
26  172842  ~
27  173216  ~
28  173760  ~
29  174976  ~
30  175751  ~
31  176672  ~
32  177216  ~
33  179040  ~
34  179584  ~
35  199264  ~
36  200032  ~
37  200640  ~
38  202915  ~
39  210976  ~
40  211522  ~
41  212128  ~
42  212672  ~
43  213888  ~
44  214432  ~
45  217169  |
46  223680  ~
47  224448  ~
48  224896  ~
49  226809  ~
50  227392  ~
51  227695  |
52  228768  ~
53  229952  ~
                   0
0       1.000000e-02
1       2.000000e-02
2       1.212660e-16
3       4.000000e-02
4       4.000000e-02
...              ...
230395  1.400000e-01
230396  1.500000e-01
230397  1.300000e-01
230398  9.000000e-02
230399  1.200000e-01

[230400 rows x 1 columns]
           0  1
0         65  N
1        163  N
2        260  N
3        357  N
4        454  N
...      ... ..
2293  229973  N
2294  230085  N
2295  230200  N
2296  230250  V
2297  230325  N

[2298 rows x 2 columns]
          0  1
0      1210  |
1      2880  |
2      5150  |
3     10900  |
4     12396  |
..      ... ..
115  224808  |
116  225260  |
117  228586  |
118  229044  |
119  230294  |

[120 rows x 2 columns]
           0
0       0.30
1       0.35
2       0.46
3       0.42
4       0.39
...      ...
230395 -0.02
230396 -0.02
230397 -0.03
230398  0.01
230399 -0.01

[230400 rows x 1 columns]
           0  1
0          1  N
1         80  N
2        159  N
3        236  N
4        313  N
...      ... ..
3018  230028  N
3019  230104  N
3020  230180  N
3021  230258  N
3022  230337  N

[3023 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0      -2.500000e-02
1       1.950000e-01
2       6.950000e-01
3       6.300000e-01
4       4.042199e-17
...              ...
230395 -1.000000e-02
230396 -1.000000e-02
230397  1.364242e-16
230398 -5.936979e-17
230399 -3.726402e-17

[230400 rows x 1 columns]
           0  1
0         26  N
1        126  N
2        224  N
3        323  N
4        422  N
...      ... ..
1937  229839  N
1938  229979  N
1939  230119  N
1940  230260  N
1941  230399  N

[1942 rows x 2 columns]
        0  1
0   73312  ~
1   73646  ~
2   74959  ~
3   75392  ~
4   77216  ~
5   78720  ~
6   82688  ~
7   83250  ~
8   83712  ~
9   84256  ~
10  87855  ~
11  88384  ~
            0
0      -0.240
1      -0.130
2      -0.090
3      -0.160
4      -0.090
...       ...
230395 -0.090
230396 -0.010
230397  0.330
230398  0.965
230399  1.600

[230400 rows x 1 columns]
           0  1
0         97  N
1        222  N
2        348  N
3        473  N
4        598  N
...      ... ..
1769  229686  N
1770  229826  N
1771  229971  N
1772  230114  N
1773  230255  N

[1774 rows x 2 columns]
        0  1
0  111428  |
1  120595  |
2  189942  |
           0
0      -0.34
1      -0.37
2      -0.40
3      -0.46
4      -0.50
...      ...
230395 -0.11
230396 -0.11
230397 -0.08
230398 -0.10
230399 -0.35

[230400 rows x 1 columns]
           0  1
0         70  N
1        163  N
2        255  N
3        349  N
4        443  N
...      ... ..
2539  230001  N
2540  230096  N
2541  230189  N
2542  230279  N
2543  230368  N

[2544 rows x 2 columns]
         0  1
0   133274  |
1   134011  |
2   136170  |
3   136620  |
4   136728  |
5   136783  |
6   137009  |
7   137064  |
8   197472  ~
9   198048  ~
10  201458  ~
11  201613  ~
12  201962  |
13  202282  ~
14  202848  ~
15  203424  ~
                   0
0      -5.000000e-02
1      -3.000000e-02
2       2.000000e-02
3       2.000000e-02
4      -2.324264e-16
...              ...
230395 -7.000000e-02
230396 -6.000000e-02
230397 -4.000000e-02
230398 -4.000000e-02
230399 -2.000000e-02

[230400 rows x 1 columns]
           0  1
0        118  N
1        238  N
2        353  N
3        468  N
4        583  N
...      ... ..
1898  229886  N
1899  230008  N
1900  230130  N
1901  230252  N
1902  230374  N

[1903 rows x 2 columns]
         0  1
0     4741  |
1     5100  |
2     7218  |
3    10678  |
4    16154  |
5    29716  |
6    33170  |
7    39371  |
8    42628  |
9    46106  |
10   52440  |
11   57273  |
12   58643  |
13   81146  |
14   94125  |
15   96693  |
16   98585  |
17  103871  |
18  111263  |
19  118411  |
20  119604  |
21  120847  |
22  124865  |
23  131637  |
24  137749  |
25  153132  |
26  159518  |
27  167417  |
28  178196  |
29  185752  |
30  186624  ~
31  186656  ~
32  187222  ~
33  187264  ~
34  194182  |
35  196861  |
36  197118  |
37  197699  |
38  198927  |
39  200324  |
40  211173  |
41  216907  |
42  218354  |
           0
0      -0.64
1      -1.28
2      -1.57
3      -1.45
4      -0.91
...      ...
230395 -0.05
230396 -0.06
230397 -0.02
230398 -0.05
230399 -0.01

[230400 rows x 1 columns]
           0  1
0         27  N
1        191  N
2        353  N
3        515  N
4        676  N
...      ... ..
1431  229644  N
1432  229822  N
1433  230000  N
1434  230182  N
1435  230362  N

[1436 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.045
1      -0.025
2      -0.025
3      -0.015
4       0.005
...       ...
230395  0.145
230396  0.175
230397  0.205
230398  0.235
230399  0.255

[230400 rows x 1 columns]

           0  1
0         96  N
1        242  N
2        395  N
3        479  V
4        682  N
...      ... ..
1837  229743  N
1838  229874  N
1839  230008  N
1840  230141  N
1841  230275  N

[1842 rows x 2 columns]
         0  1
0    73664  ~
1    73717  ~
2    73905  |
3    73992  |
4    74240  ~
5    74272  ~
6   118624  |
7   121952  ~
8   122272  ~
9   122292  |
10  122509  |
11  122531  ~
12  122816  ~
13  123040  ~
14  125056  ~
15  126976  ~
16  127392  ~
17  127583  |
18  127669  |
19  127959  ~
20  128512  ~
21  129088  ~
22  129376  ~
23  129386  |
24  129696  ~
25  129920  ~
26  143360  ~
27  143392  ~
28  143598  |
29  143936  ~
30  143968  ~
                   0
0       8.000000e-02
1       5.000000e-02
2       7.000000e-02
3       3.000000e-02
4       2.000000e-02
...              ...
230395 -8.000000e-02
230396 -5.000000e-02
230397 -5.000000e-02
230398 -1.000000e-02
230399 -7.073848e-17

[230400 rows x 1 columns]
           0  1
0         49  N
1        149  N
2        217  S
3        337  N
4        441  N
...      ... ..
2347  229979  N
2348  230076  N
2349  230172  N
2350  230265  N
2351  230365  N

[2352 rows x 2 columns]
        0  1
0   87062  |
1  185653  |
2  228693  |
3  228888  |
            0
0       0.005
1      -0.035
2       0.005
3      -0.055
4       0.020
...       ...
230395 -0.150
230396 -0.100
230397 -0.140
230398 -0.050
230399 -0.080

[230400 rows x 1 columns]
           0  1
0         49  N
1        124  N
2        198  N
3        272  N
4        347  N
...      ... ..
3128  230076  N
3129  230132  S
3130  230218  N
3131  230293  N
3132  230366  N

[3133 rows x 2 columns]
        0  1
0  212704  ~
1  213280  ~
                   0
0      -1.000000e-02
1       1.000000e-02
2       2.021099e-17
3       2.526374e-18
4       4.547474e-17
...              ...
230395  1.750000e-01
230396  2.150000e-01
230397  1.850000e-01
230398  1.750000e-01
230399  1.350000e-01

[230400 rows x 1 columns]
           0  1
0         47  N
1        152  N
2        242  N
3        351  N
4        439  S
...      ... ..
2329  229975  N
2330  230069  N
2331  230161  N
2332  230253  N
2333  230345  N

[2334 rows x 2 columns]
        0  1
0       0  "
1   66586  |
2  175709  |
3  214848  |
                   0
0      -1.000000e-02
1      -1.000000e-02
2       1.000000e-02
3       1.000000e-02
4      -5.052748e-17
...              ...
230395 -4.000000e-02
230396 -7.000000e-02
230397 -2.000000e-02
230398 -3.000000e-02
230399 -3.000000e-02

[230400 rows x 1 columns]
           0  1
0         43  N
1        123  N
2        203  N
3        283  N
4        363  N
...      ... ..
2856  230048  N
2857  230104  S
2858  230188  N
2859  230270  N
2860  230348  N

[2861 rows x 2 columns]
        0  1
0   80785  |
1   87140  |
2  100074  |
           0
0      -0.12
1      -0.09
2      -0.03
3      -0.12
4      -0.09
...      ...
230395  0.18
230396  0.18
230397  0.18
230398  0.17
230399  0.15

[230400 rows x 1 columns]
           0  1
0         59  N
1        168  N
2        268  N
3        342  S
4        452  N
...      ... ..
2414  229979  N
2415  230052  S
2416  230151  N
2417  230242  N
2418  230334  N

[2419 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0      -2.000000e-01
1      -1.600000e-01
2      -1.700000e-01
3      -1.600000e-01
4      -1.450000e-01
...              ...
230395 -4.000000e-02
230396 -6.000000e-02
230397 -3.500000e-02
230398 -4.042199e-17
230399  0.000000e+00

[230400 rows x 1 columns]
           0  1
0         12  N
1         90  N
2        173  N
3        258  N
4        306  S
...      ... ..
2793  230062  N
2794  230144  N
2795  230225  N
2796  230307  N
2797  230388  N

[2798 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.180
1      -0.285
2      -0.805
3      -1.385
4      -1.785
...       ...
230395  0.075
230396  0.105
230397  0.110
230398  0.135
230399  0.135

[230400 rows x 1 columns]
           0  1
0        101  N
1        189  N
2        277  N
3        366  N
4        452  N
...      ... ..
2656  229965  N
2657  230050  N
2658  230140  N
2659  230232  N
2660  230318  N

[2661 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0      -3.031649e-17
1       2.250000e-01
2       2.750000e-01
3       9.500000e-02
4      -2.700000e-01
...              ...
230395 -2.000000e-02
230396 -3.031649e-17
230397  1.500000e-02
230398  2.000000e-02
230399  2.500000e-02

[230400 rows x 1 columns]
           0  1
0         54  N
1        165  N
2        276  N
3        386  N
4        498  N
...      ... ..
1857  229790  N
1858  229922  N
1859  230050  N
1860  230179  N
1861  230308  N

[1862 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
           0
0       0.01
1      -0.02
2      -0.02
3       0.05
4       0.03
...      ...
230395 -0.20
230396 -0.19
230397 -0.22
230398 -0.20
230399 -0.17

[230400 rows x 1 columns]
           0  1
0         15  N
1        150  N
2        211  S
3        352  N
4        497  N
...      ... ..
1908  229843  S
1909  229964  N
1910  230079  N
1911  230193  N
1912  230294  N

[1913 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0       5.052748e-18
1       1.000000e-02
2      -2.526374e-18
3      -1.500000e-02
4      -1.500000e-02
...              ...
230395  5.000000e-03
230396  5.000000e-03
230397 -1.000000e-02
230398  6.947529e-18
230399 -6.315935e-18

[230400 rows x 1 columns]
           0  1
0        119  N
1        228  N
2        343  N
3        455  N
4        569  N
...      ... ..
1962  229908  N
1963  230032  N
1964  230149  N
1965  230274  N
1966  230394  N

[1967 rows x 2 columns]
       0  1
0  21969  |
            0
0      -0.075
1      -0.690
2      -0.495
3      -0.220
4      -0.025
...       ...
230395 -0.700
230396 -0.490
230397 -0.210
230398 -0.030
230399 -0.030

[230400 rows x 1 columns]
           0  1
0         22  N
1        120  N
2        219  N
3        318  N
4        414  N
...      ... ..
2381  229948  N
2382  230042  N
2383  230137  N
2384  230232  N
2385  230328  N

[2386 rows x 2 columns]
        0  1
0  100772  |
1  102720  ~
2  103360  ~
3  107906  |
4  215425  |
                   0
0      -7.500000e-02
1      -3.000000e-02
2      -2.000000e-02
3      -1.010550e-17
4      -2.000000e-02
...              ...
230395 -1.550000e-01
230396 -1.550000e-01
230397 -1.150000e-01
230398 -1.250000e-01
230399 -1.450000e-01

[230400 rows x 1 columns]
           0  1
0         93  N
1        224  N
2        352  N
3        476  N
4        606  N
...      ... ..
1849  229697  N
1850  229839  N
1851  229980  N
1852  230123  N
1853  230265  N

[1854 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0       0.175
1       0.185
2       0.185
3       0.160
4       0.150
...       ...
230395 -0.010
230396  0.005
230397  0.105
230398 -0.005
230399 -0.105

[230400 rows x 1 columns]
           0  1
0         59  N
1        140  N
2        226  N
3        312  N
4        398  N
...      ... ..
2554  229959  N
2555  230052  N
2556  230145  N
2557  230240  N
2558  230336  N

[2559 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.180
1      -0.195
2      -0.215
3      -0.165
4      -0.140
...       ...
230395 -0.045
230396 -0.025
230397 -0.020
230398 -0.025
230399 -0.025

[230400 rows x 1 columns]
           0  1
0          3  N
1         53  V
2        159  N
3        238  N
4        317  N
...      ... ..
2703  230001  N
2704  230096  N
2705  230193  N
2706  230288  N
2707  230386  N

[2708 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0       1.200000e+00
1       5.600000e-01
2       4.042199e-17
3      -4.800000e-01
4      -3.250000e-01
...              ...
230395 -9.000000e-02
230396 -1.050000e-01
230397 -1.050000e-01
230398  4.547474e-17
230399 -5.000000e-03

[230400 rows x 1 columns]
           0  1
0         53  N
1        196  N
2        338  N
3        486  N
4        625  N
...      ... ..
1704  229791  N
1705  229852  S
1706  230019  N
1707  230149  N
1708  230283  N

[1709 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.010
1      -0.010
2       0.005
3      -0.010
4      -0.025
...       ...
230395  0.025
230396 -0.010
230397 -0.015
230398 -0.035
230399 -0.035

[230400 rows x 1 columns]

           0  1
0         70  N
1        152  N
2        231  N
3        279  S
4        366  N
...      ... ..
2882  230009  N
2883  230088  N
2884  230169  N
2885  230253  N
2886  230336  N

[2887 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0       3.700000e-01
1       3.850000e-01
2       3.800000e-01
3       3.950000e-01
4       3.800000e-01
...              ...
230395  8.000000e-02
230396  1.500000e-02
230397  1.000000e-02
230398 -3.637979e-16
230399 -4.042199e-16

[230400 rows x 1 columns]
           0  1
0         11  N
1        145  N
2        280  N
3        419  N
4        555  N
...      ... ..
1676  229837  N
1677  229974  N
1678  230107  N
1679  230243  N
1680  230383  N

[1681 rows x 2 columns]
      0  1
0  6720  ~
1  6893  |
2  6978  |
3  7264  ~
            0
0      -0.095
1      -0.095
2      -0.105
3      -0.115
4      -0.105
...       ...
230395 -0.060
230396 -0.060
230397 -0.060
230398 -0.060
230399 -0.050

[230400 rows x 1 columns]
           0  1
0         38  N
1        140  N
2        197  V
3        340  N
4        440  N
...      ... ..
1757  229846  N
1758  229984  N
1759  230118  N
1760  230251  N
1761  230385  N

[1762 rows x 2 columns]
         0  1
0     6560  ~
1     6761  |
2     6849  |
3     6874  |
4     6958  |
..     ... ..
69  224960  ~
70  225664  ~
71  229587  ~
72  230112  ~
73  230165  |

[74 rows x 2 columns]
           0
0      -0.10
1      -0.08
2      -0.15
3      -0.12
4      -0.08
...      ...
230395 -0.12
230396 -0.07
230397 -0.07
230398 -0.03
230399 -0.08

[230400 rows x 1 columns]
           0  1
0         30  N
1         78  N
2        131  N
3        183  N
4        234  N
...      ... ..
4254  230156  N
4255  230215  N
4256  230274  N
4257  230334  N
4258  230392  N

[4259 rows x 2 columns]
         0  1
0      868  ~
1     1440  ~
2     2056  ~
3     3876  ~
4     4553  ~
5     5472  ~
6     5901  ~
7     6432  ~
8    10864  ~
9    11399  ~
10   12534  ~
11   12635  |
12   12817  ~
13   13070  ~
14   13449  ~
15   13986  ~
16   14985  ~
17   15254  |
18   15473  |
19   15680  ~
20   17076  ~
21   19135  ~
22   19697  ~
23   21376  ~
24   22581  ~
25   23019  ~
26   23587  ~
27   24647  ~
28   25792  ~
29  128897  |
            0
0      -0.185
1      -0.215
2      -0.245
3      -0.235
4      -0.245
...       ...
230395 -0.455
230396 -0.320
230397 -0.075
230398 -0.055
230399 -0.065

[230400 rows x 1 columns]
           0  1
0         88  N
1        201  N
2        312  N
3        425  N
4        540  N
...      ... ..
2156  229898  N
2157  230015  N
2158  230133  N
2159  230253  N
2160  230370  N

[2161 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0      -7.073848e-17
1      -4.042199e-17
2       0.000000e+00
3      -1.010550e-17
4       4.042199e-17
...              ...
230395  1.500000e-02
230396 -1.000000e-02
230397 -5.000000e-03
230398 -2.500000e-02
230399 -2.500000e-02

[230400 rows x 1 columns]
           0  1
0          4  N
1        126  N
2        248  N
3        369  N
4        490  N
...      ... ..
1833  229896  N
1834  230034  N
1835  230172  N
1836  230296  N
1837  230388  S

[1838 rows x 2 columns]
        0  1
0  212244  ~
1  212768  ~
            0
0      -0.290
1      -0.300
2      -0.940
3      -0.940
4      -0.305
...       ...
230395 -1.130
230396 -1.710
230397 -1.680
230398 -1.320
230399 -1.030

[230400 rows x 1 columns]
           0  1
0         85  N
1        152  V
2        257  N
3        342  N
4        428  N
...      ... ..
2623  229990  N
2624  230089  N
2625  230187  N
2626  230258  V
2627  230385  N

[2628 rows x 2 columns]
          0  1
0       192  |
1       536  |
2       790  |
3      2451  |
4      4042  |
..      ... ..
136  215474  |
137  219270  |
138  219818  |
139  223565  |
140  225698  |

[141 rows x 2 columns]
           0
0       3.95
1       3.53
2       2.89
3       2.25
4       1.61
...      ...
230395 -0.43
230396 -0.29
230397 -0.22
230398 -0.19
230399 -0.18

[230400 rows x 1 columns]
           0  1
0         48  N
1        128  N
2        215  N
3        297  N
4        379  N
...      ... ..
2659  229998  N
2660  230084  N
2661  230169  N
2662  230251  N
2663  230337  N

[2664 rows x 2 columns]
        0  1
0  112143  +
            0
0       0.145
1       0.125
2       0.145
3       0.145
4       0.145
...       ...
230395 -0.020
230396 -0.020
230397 -0.040
230398 -0.030
230399 -0.030

[230400 rows x 1 columns]
           0  1
0         85  N
1        186  N
2        291  N
3        393  N
4        496  N
...      ... ..
2226  229925  V
2227  230058  N
2228  230160  N
2229  230265  N
2230  230370  N

[2231 rows x 2 columns]
         0  1
0    12336  |
1    46789  |
2    87947  |
3   104131  |
4   126071  |
5   126690  |
6   156525  |
7   157439  |
8   178748  |
9   178956  |
10  185836  |
11  187148  |
12  193527  |
13  222140  |
           0
0      -0.20
1      -0.23
2      -0.24
3      -0.25
4      -0.25
...      ...
230395 -0.30
230396 -0.33
230397 -0.36
230398 -0.38
230399 -0.43

[230400 rows x 1 columns]
           0  1
0         95  N
1        168  V
2        267  N
3        359  N
4        426  V
...      ... ..
2727  229973  N
2728  230063  N
2729  230131  V
2730  230245  N
2731  230336  N

[2732 rows x 2 columns]
          0  1
0       742  |
1       998  ~
2      1253  |
3      1536  ~
4      1733  |
..      ... ..
372  228339  ~
373  228899  ~
374  229641  |
375  229897  |
376  230165  |

[377 rows x 2 columns]
           0
0       1.56
1       0.92
2       0.28
3      -0.36
4      -0.29
...      ...
230395  0.04
230396  0.01
230397  0.04
230398  0.01
230399  0.03

[230400 rows x 1 columns]
           0  1
0         18  N
1         90  N
2        143  S
3        192  S
4        262  N
...      ... ..
2535  230059  N
2536  230150  N
2537  230240  N
2538  230325  N
2539  230383  V

[2540 rows x 2 columns]
         0  1
0      225  ~
1      992  ~
2     1541  ~
3     1975  ~
4     2515  ~
5     3232  ~
6     3465  ~
7     3776  ~
8     4033  ~
9     5222  ~
10    6092  ~
11    6560  ~
12    6991  ~
13   10641  ~
14   11301  |
15   11488  |
16   11646  |
17   11805  |
18   12319  |
19   12780  ~
20   12800  ~
21   17120  ~
22   17676  ~
23   17696  ~
24   43680  ~
25   46240  ~
26   66761  ~
27   67296  ~
28   67559  |
29   67936  ~
30   69184  ~
31   75872  ~
32   76448  ~
33  209536  ~
34  210080  ~
35  220224  ~
36  220768  ~
            0
0      -0.095
1      -0.070
2      -0.060
3      -0.090
4      -0.070
...       ...
230395 -0.495
230396 -0.515
230397 -0.525
230398 -0.525
230399 -0.555

[230400 rows x 1 columns]
           0  1
0         28  N
1        109  N
2        190  N
3        271  N
4        352  N
...      ... ..
2848  230028  N
2849  230106  N
2850  230183  N
2851  230260  N
2852  230337  N

[2853 rows x 2 columns]
         0  1
0    60384  ~
1    60866  |
2    60960  ~
3    61152  ~
4    61696  ~
5    62240  ~
6    79300  |
7    79379  |
8    79454  |
9   208563  |
10  213184  ~
11  213566  |
12  213728  ~
13  213782  |
14  220807  ~
15  221344  ~
16  221792  ~
17  221824  ~
18  222012  |
19  222336  ~
20  222379  ~
21  226320  ~
22  226880  ~
                   0
0      -6.063298e-17
1       4.000000e-02
2       3.000000e-02
3       4.042199e-17
4       3.000000e-02
...              ...
230395  2.100000e-01
230396  1.400000e-01
230397  3.000000e-02
230398 -1.000000e-02
230399  5.052748e-18

[230400 rows x 1 columns]
           0  1
0         26  N
1         83  S
2        142  V
3        271  N
4        359  N
...      ... ..
2579  229987  N
2580  230079  N
2581  230172  N
2582  230265  N
2583  230358  N

[2584 rows x 2 columns]
         0  1
0      839  ~
1     1299  ~
2     1824  ~
3    11104  ~
4    11136  ~
5    11623  ~
6    11697  ~
7    21728  ~
8    21774  |
9    22272  ~
10   22816  ~
11   25440  ~
12   26039  ~
13   31744  ~
14   32323  ~
15   40320  ~
16   40568  ~
17   40577  |
18   40657  |
19   41120  ~
20   41664  ~
21   76230  |
22  115552  ~
23  116479  ~
24  144783  ~
25  145392  ~
           0
0       0.25
1       0.18
2       0.09
3      -0.05
4      -0.23
...      ...
230395  0.36
230396  0.32
230397  0.27
230398  0.22
230399  0.18

[230400 rows x 1 columns]

           0  1
0         45  N
1        146  N
2        251  N
3        353  N
4        453  N
...      ... ..
2175  229913  N
2176  230012  N
2177  230109  N
2178  230207  N
2179  230303  N

[2180 rows x 2 columns]
        0  1
0   69248  ~
1   69805  ~
2  218513  |
3  220322  |
4  220628  |
5  221922  |
6  222114  |
           0
0       0.09
1       0.19
2       0.00
3       0.14
4       0.15
...      ...
230395 -0.15
230396 -0.09
230397 -0.12
230398 -0.25
230399 -0.45

[230400 rows x 1 columns]
           0  1
0         12  N
1         72  N
2        128  N
3        184  N
4        245  N
...      ... ..
3537  230082  S
3538  230156  N
3539  230236  N
3540  230308  N
3541  230380  N

[3542 rows x 2 columns]
         0  1
0    10432  ~
1    11008  ~
2    11488  ~
3    12032  ~
4    12928  ~
5    13472  ~
6   108305  |
7   108832  ~
8   109450  ~
9   110593  ~
10  111296  ~
11  122070  ~
12  122869  ~
13  210093  ~
14  210696  ~
                   0
0       2.100000e-01
1       2.700000e-01
2       3.200000e-01
3      -8.084397e-17
4       1.000000e-02
...              ...
230395 -5.800000e-01
230396 -5.600000e-01
230397 -5.700000e-01
230398 -5.900000e-01
230399 -6.100000e-01

[230400 rows x 1 columns]
           0  1
0        104  N
1        204  N
2        261  V
3        409  N
4        509  N
...      ... ..
2413  229996  N
2414  230098  N
2415  230199  N
2416  230254  V
2417  230400  N

[2418 rows x 2 columns]
         0  1
0     4008  |
1    39378  |
2    39791  ~
3    40512  ~
4    41006  ~
5    41120  ~
6    41318  |
7    41360  |
8    41454  |
9    41478  |
10   41599  |
11   42169  |
12   42304  ~
13   42528  ~
14   53472  ~
15   54016  ~
16   67395  |
17   68962  |
18   70496  ~
19   70565  |
20   70667  |
21   70741  |
22   71040  ~
23   71264  ~
24   71682  |
25   71943  |
26   72000  ~
27   72212  |
28   72282  |
29   72480  |
30   72544  ~
31   73014  ~
32   73230  |
33   73568  ~
34   74304  ~
35   74570  |
36   74623  |
37   75024  |
38   75161  |
39   75328  ~
40   75552  ~
41   80643  |
42   88006  ~
43   88552  ~
44  158310  |
                   0
0       2.700000e-01
1       5.700000e-01
2       3.600000e-01
3      -2.200000e-01
4      -3.300000e-01
...              ...
230395 -1.400000e-01
230396 -4.000000e-02
230397 -1.212660e-16
230398  5.052748e-17
230399 -2.021099e-16

[230400 rows x 1 columns]
           0  1
0         86  N
1        178  N
2        272  N
3        352  N
4        455  N
...      ... ..
2467  229911  N
2468  229992  S
2469  230101  N
2470  230201  N
2471  230301  N

[2472 rows x 2 columns]
          0  1
0      1584  ~
1      2123  ~
2      7872  ~
3      9056  ~
4     15592  |
..      ... ..
105  192174  |
106  192544  ~
107  208797  |
108  215424  ~
109  215968  ~

[110 rows x 2 columns]
                   0
0       1.818989e-16
1       2.000000e-02
2       4.600000e-01
3      -1.000000e-01
4       4.400000e-01
...              ...
230395 -2.300000e-01
230396 -1.800000e-01
230397 -2.100000e-01
230398 -7.000000e-02
230399  4.300000e-01

[230400 rows x 1 columns]
           0  1
0         65  N
1        198  N
2        329  N
3        460  N
4        590  N
...      ... ..
2183  229900  S
2184  230024  N
2185  230134  N
2186  230242  N
2187  230347  N

[2188 rows x 2 columns]
          0  1
0        34  |
1       167  |
2       299  |
3       429  |
4       560  |
..      ... ..
404  207424  ~
405  207739  |
406  208384  ~
407  220197  |
408  221665  |

[409 rows x 2 columns]
           0
0       0.11
1       0.10
2       0.06
3       0.07
4       0.03
...      ...
230395 -0.02
230396 -0.02
230397  0.02
230398 -0.03
230399  0.05

[230400 rows x 1 columns]
           0  1
0         55  S
1        138  N
2        211  N
3        284  N
4        357  N
...      ... ..
3119  230051  N
3120  230124  N
3121  230197  N
3122  230271  N
3123  230344  N

[3124 rows x 2 columns]
        0  1
0   83299  |
1  208896  ~
2  209504  ~
3  223231  ~
4  223881  ~
                   0
0      -1.200000e-01
1      -1.500000e-01
2      -1.700000e-01
3      -1.800000e-01
4      -1.500000e-01
...              ...
230395 -1.000000e-02
230396  3.637979e-16
230397  2.000000e-02
230398  6.000000e-02
230399  3.000000e-02

[230400 rows x 1 columns]
           0  1
0         39  N
1        156  N
2        270  N
3        386  N
4        501  N
...      ... ..
1890  229796  N
1891  229930  N
1892  230058  N
1893  230188  N
1894  230316  N

[1895 rows x 2 columns]
         0  1
0    70192  ~
1    70720  ~
2    89700  ~
3    90240  ~
4    90483  ~
5    92128  ~
6   179143  ~
7   180960  ~
8   182167  ~
9   182720  ~
10  184224  ~
11  186688  ~
                   0
0       2.000000e-02
1       0.000000e+00
2       1.000000e-02
3       3.000000e-02
4      -8.589672e-17
...              ...
230395 -2.000000e-02
230396 -6.000000e-02
230397 -3.000000e-02
230398 -4.000000e-02
230399 -8.000000e-02

[230400 rows x 1 columns]
           0  1
0         11  N
1        146  N
2        280  N
3        414  N
4        547  N
...      ... ..
3157  229922  V
3158  230047  N
3159  230142  N
3160  230238  N
3161  230295  V

[3162 rows x 2 columns]
          0  1
0      2768  |
1      3723  |
2      3890  |
3      4667  |
4      5925  |
..      ... ..
534  195893  |
535  196203  |
536  196820  |
537  207178  |
538  219415  |

[539 rows x 2 columns]
           0
0      -0.25
1      -0.22
2      -0.26
3      -0.25
4      -0.29
...      ...
230395 -0.11
230396 -0.03
230397  0.13
230398 -0.01
230399 -0.14

[230400 rows x 1 columns]
           0  1
0        116  N
1        224  N
2        290  S
3        378  N
4        493  N
...      ... ..
2661  230081  N
2662  230148  V
2663  230249  N
2664  230314  V
2665  230386  N

[2666 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.090
1      -0.010
2      -0.020
3      -0.010
4       0.010
...       ...
230395 -0.065
230396 -0.070
230397 -0.070
230398 -0.070
230399 -0.080

[230400 rows x 1 columns]
           0  1
0         18  N
1        133  N
2        247  N
3        315  V
4        417  N
...      ... ..
2995  229953  N
2996  230063  N
2997  230121  V
2998  230220  N
2999  230325  N

[3000 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0      -4.000000e-02
1      -6.000000e-02
2      -5.000000e-03
3       2.500000e-02
4      -5.052748e-18
...              ...
230395  3.000000e-02
230396 -6.947529e-17
230397 -8.842310e-18
230398  8.842310e-18
230399  5.000000e-03

[230400 rows x 1 columns]
           0  1
0         61  N
1        133  N
2        204  N
3        275  N
4        346  N
...      ... ..
3343  230072  N
3344  230144  V
3345  230229  N
3346  230289  V
3347  230374  N

[3348 rows x 2 columns]
         0  1
0    19716  ~
1    20256  ~
2    21192  ~
3    21856  ~
4    22183  |
..     ... ..
92  196821  ~
93  197312  ~
94  199866  ~
95  221602  ~
96  222176  ~

[97 rows x 2 columns]
           0
0      -0.66
1      -0.62
2      -0.72
3      -0.61
4      -0.74
...      ...
230395 -0.80
230396 -0.87
230397 -0.94
230398 -1.00
230399 -1.15

[230400 rows x 1 columns]
           0  1
0         20  N
1        127  N
2        231  N
3        341  N
4        450  N
...      ... ..
2156  229926  S
2157  230028  N
2158  230100  S
2159  230194  N
2160  230277  S

[2161 rows x 2 columns]
        0  1
0  165069  ~
1  165663  ~
           0
0       0.05
1       0.04
2       0.05
3       0.10
4       0.10
...      ...
230395  0.02
230396 -0.01
230397 -0.08
230398 -0.05
230399 -0.12

[230400 rows x 1 columns]
           0  1
0        103  N
1        202  N
2        301  N
3        402  N
4        503  N
...      ... ..
2673  230015  S
2674  230116  N
2675  230177  V
2676  230285  N
2677  230341  V

[2678 rows x 2 columns]
          0  1
0    127264  ~
1    127566  ~
2    127624  |
3    128052  ~
4    128128  ~
..      ... ..
108  220915  |
109  221218  |
110  221269  |
111  222102  |
112  225535  |

[113 rows x 2 columns]
           0
0      -0.41
1      -0.46
2      -0.46
3      -0.42
4      -0.46
...      ...
230395  0.04
230396  0.02
230397  0.07
230398  0.05
230399  0.01

[230400 rows x 1 columns]
           0  1
0         84  N
1        200  N
2        312  N
3        422  N
4        538  N
...      ... ..
1791  229833  N
1792  229976  N
1793  230120  N
1794  230253  N
1795  230384  N

[1796 rows x 2 columns]
        0  1
0  151360  ~
1  151385  |
2  151765  |
3  152032  ~
4  154190  ~
5  154688  ~
6  154707  |

           0
0       0.37
1       0.50
2       0.57
3       0.68
4       0.73
...      ...
230395 -0.11
230396 -0.11
230397 -0.03
230398 -0.08
230399 -0.06

[230400 rows x 1 columns]
           0  1
0          3  N
1        124  N
2        242  N
3        358  N
4        479  N
...      ... ..
1976  229860  N
1977  229979  N
1978  230098  N
1979  230219  N
1980  230343  N

[1981 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.075
1      -0.085
2      -0.145
3       0.035
4       0.395
...       ...
230395 -0.125
230396 -0.105
230397 -0.115
230398 -0.115
230399 -0.105

[230400 rows x 1 columns]
           0  1
0         22  N
1        153  N
2        283  N
3        418  N
4        548  N
...      ... ..
1679  229777  N
1680  229913  N
1681  230048  N
1682  230186  N
1683  230322  N

[1684 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
           0
0      -0.10
1      -0.10
2      -0.09
3      -0.05
4      -0.09
...      ...
230395 -0.19
230396 -0.20
230397 -0.15
230398 -0.19
230399 -0.26

[230400 rows x 1 columns]
           0  1
0         22  N
1        137  N
2        252  N
3        368  N
4        482  N
...      ... ..
2235  229952  N
2236  230056  N
2237  230160  N
2238  230263  N
2239  230368  N

[2240 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
           0
0      -0.04
1      -0.05
2      -0.05
3      -0.04
4      -0.05
...      ...
230395  0.79
230396  0.80
230397  0.82
230398  0.86
230399  0.86

[230400 rows x 1 columns]
           0  1
0         56  N
1        162  N
2        266  N
3        372  N
4        478  N
...      ... ..
2047  229915  N
2048  230031  N
2049  230127  S
2050  230261  N
2051  230378  N

[2052 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0       4.000000e-02
1       9.000000e-02
2      -8.000000e-02
3       2.000000e-02
4       3.233759e-16
...              ...
230395 -6.000000e-02
230396 -1.100000e-01
230397 -1.200000e-01
230398 -1.400000e-01
230399 -1.900000e-01

[230400 rows x 1 columns]
           0  1
0        100  N
1        208  N
2        322  N
3        432  N
4        523  N
...      ... ..
2136  229853  N
2137  229975  N
2138  230066  S
2139  230191  N
2140  230313  N

[2141 rows x 2 columns]
        0  1
0  118852  |
            0
0      -0.180
1       0.000
2       0.040
3       0.040
4       0.030
...       ...
230395 -0.005
230396 -0.005
230397  0.005
230398 -0.005
230399 -0.005

[230400 rows x 1 columns]
           0  1
0         13  N
1        131  N
2        232  N
3        355  N
4        472  N
...      ... ..
2033  229918  N
2034  230033  N
2035  230148  N
2036  230267  N
2037  230387  N

[2038 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.030
1      -0.040
2      -0.035
3      -0.040
4      -0.020
...       ...
230395  0.020
230396  0.030
230397  0.035
230398  0.035
230399  0.035

[230400 rows x 1 columns]
           0  1
0         47  N
1        150  N
2        253  N
3        356  N
4        464  N
...      ... ..
1906  229850  S
1907  230002  N
1908  230071  V
1909  230219  N
1910  230360  N

[1911 rows x 2 columns]
         0  1
0      384  ~
1     1024  ~
2    36480  ~
3    37024  ~
4    45248  ~
5    45920  ~
6    60801  |
7    91959  |
8   176082  |
9   208193  |
10  227414  ~
11  227626  |
12  227968  ~
13  228087  |
14  229428  ~
15  229952  ~
           0
0       0.33
1       0.27
2       0.17
3       0.19
4       0.12
...      ...
230395 -0.09
230396  0.04
230397 -0.06
230398 -0.04
230399 -0.02

[230400 rows x 1 columns]
           0  1
0         66  N
1        169  N
2        277  N
3        385  N
4        491  N
...      ... ..
2057  229922  N
2058  230024  N
2059  230140  N
2060  230246  N
2061  230353  N

[2062 rows x 2 columns]
         0  1
0    14791  |
1    17696  ~
2    18272  ~
3    21703  |
4    22273  ~
5    22838  ~
6    76000  ~
7    77280  ~
8    82880  ~
9    84224  ~
10  166528  ~
11  167084  ~
12  169044  ~
13  169568  ~
14  169845  |
15  169903  |
16  169955  |
17  170091  |
18  170144  ~
19  170272  ~
20  171200  ~
21  171744  ~
22  220160  ~
23  220704  ~
24  223036  |
25  225312  ~
26  226560  ~
           0
0       0.28
1       0.26
2       0.27
3       0.23
4       0.20
...      ...
230395 -0.15
230396 -0.03
230397 -0.14
230398 -0.17
230399 -0.13

[230400 rows x 1 columns]
           0  1
0         52  N
1        119  N
2        175  S
3        252  N
4        298  S
...      ... ..
3482  230131  N
3483  230196  N
3484  230262  N
3485  230327  N
3486  230393  N

[3487 rows x 2 columns]
   0  1
0  0  "
            0
0      -0.830
1      -0.830
2      -0.890
3      -0.890
4      -0.920
...       ...
230395  2.610
230396  3.245
230397  3.650
230398  3.010
230399  2.370

[230400 rows x 1 columns]
           0  1
0         26  S
1        147  N
2        245  S
3        371  N
4        466  S
...      ... ..
2258  229908  N
2259  229995  S
2260  230125  N
2261  230214  S
2262  230348  N

[2263 rows x 2 columns]
         0  1
0     9866  ~
1    10560  ~
2    17065  ~
3    17375  |
4    18000  ~
5    18656  ~
6    19211  ~
7    19841  ~
8    20416  ~
9    20567  |
10   20945  |
11   20968  ~
12   21312  ~
13   71943  |
14   74016  ~
15   74880  ~
16  104898  ~
17  105440  ~
18  105617  ~
19  106162  ~
20  107710  |
21  107780  ~
22  107993  ~
23  108189  |
24  108232  |
25  108301  |
26  108640  ~
27  108800  ~
28  109150  ~
29  109664  ~
30  111264  ~
31  111296  ~
32  111559  |
33  111840  ~
34  184544  ~
35  185120  ~
36  212582  ~
37  212719  |
38  213248  ~
            0
0      -0.100
1      -0.080
2      -0.080
3      -0.090
4      -0.120
...       ...
230395  0.055
230396  0.015
230397  0.085
230398  0.055
230399  0.085

[230400 rows x 1 columns]
           0  1
0         75  N
1        180  N
2        287  N
3        395  N
4        501  N
...      ... ..
1930  229863  N
1931  229985  N
1932  230110  N
1933  230229  N
1934  230352  N

[1935 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
           0
0      -0.30
1      -0.34
2      -0.33
3      -0.39
4      -0.39
...      ...
230395 -0.37
230396 -0.34
230397 -0.34
230398 -0.26
230399 -0.15

[230400 rows x 1 columns]
           0  1
0         73  N
1        195  N
2        319  N
3        439  N
4        507  S
...      ... ..
1815  229815  N
1816  229947  N
1817  230078  N
1818  230210  N
1819  230344  N

[1820 rows x 2 columns]
        0  1
0   47605  |
1  200163  |
                   0
0      -4.200000e-01
1      -3.200000e-01
2      -2.200000e-01
3      -1.800000e-01
4      -1.300000e-01
...              ...
230395 -2.600000e-01
230396 -1.300000e-01
230397 -1.000000e-02
230398  2.343212e-16
230399 -2.501110e-16

[230400 rows x 1 columns]
           0  1
0         59  N
1        141  N
2        222  N
3        303  N
4        384  N
...      ... ..
2878  230063  N
2879  230135  N
2880  230209  N
2881  230282  N
2882  230339  V

[2883 rows x 2 columns]
          0  1
0      2725  |
1      6946  |
2      8314  |
3      8656  |
4      8976  |
..      ... ..
134  219043  |
135  220506  |
136  228848  |
137  229650  |
138  229854  |

[139 rows x 2 columns]
           0
0      -0.11
1      -0.12
2      -0.06
3       0.02
4       0.07
...      ...
230395  0.01
230396 -0.02
230397 -0.04
230398 -0.01
230399 -0.03

[230400 rows x 1 columns]
           0  1
0         90  N
1        208  N
2        325  N
3        393  S
4        536  N
...      ... ..
1955  229800  N
1956  229927  N
1957  230061  N
1958  230151  S
1959  230295  N

[1960 rows x 2 columns]
         0  1
0      417  ~
1      697  |
2     1376  ~
3     1545  ~
4     1577  |
..     ... ..
89  229888  ~
90  229984  ~
91  230209  |
92  230255  |
93  230387  |

[94 rows x 2 columns]
           0
0      -0.15
1      -0.14
2      -0.11
3       0.00
4      -0.06
...      ...
230395 -0.31
230396 -0.04
230397 -0.45
230398 -0.19
230399  0.10

[230400 rows x 1 columns]
           0  1
0         52  N
1        155  N
2        258  N
3        367  N
4        471  N
...      ... ..
2218  229931  N
2219  230046  N
2220  230164  N
2221  230283  N
2222  230396  V

[2223 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
                   0
0       1.162132e-16
1      -4.042199e-17
2      -5.000000e-03
3       5.000000e-03
4      -1.212660e-16
...              ...
230395 -5.500000e-02
230396 -3.900000e-01
230397 -7.200000e-01
230398 -9.500000e-01
230399 -9.950000e-01

[230400 rows x 1 columns]

           0  1
0         50  N
1        148  N
2        246  N
3        307  V
4        443  N
...      ... ..
2685  230021  N
2686  230098  N
2687  230175  N
2688  230252  N
2689  230328  N

[2690 rows x 2 columns]
          0  1
0      4064  ~
1      4608  ~
2      8192  ~
3      8736  ~
4     12096  ~
..      ... ..
127  206451  ~
128  206944  ~
129  207040  ~
130  220192  ~
131  220768  ~

[132 rows x 2 columns]
            0
0      -0.040
1      -0.030
2      -0.040
3      -0.040
4      -0.020
...       ...
230395 -0.130
230396 -0.140
230397 -0.150
230398 -0.160
230399 -0.155

[230400 rows x 1 columns]
           0  1
0          4  N
1         97  N
2        190  N
3        282  N
4        353  S
...      ... ..
2308  229921  V
2309  230028  N
2310  230128  N
2311  230228  N
2312  230328  N

[2313 rows x 2 columns]
         0  1
0     3726  |
1    12737  |
2    15939  |
3    27067  |
4    35692  |
5    49752  |
6    58849  |
7    70818  |
8    83958  |
9    85846  |
10  102144  ~
11  103670  ~
12  110906  |
13  111308  |
14  118648  |
15  135328  ~
16  135872  ~
17  138944  ~
18  139520  ~
19  145376  ~
20  146560  ~
21  153281  |
22  154407  ~
23  154944  ~
24  158394  |
25  162240  ~
26  162916  ~
27  178603  |
28  183458  |
29  183728  |
30  197084  |
31  197210  ~
32  198176  ~
33  202688  ~
34  203232  ~
35  228642  |
36  229954  |
           0
0      -0.03
1       0.05
2       0.07
3      -0.12
4      -0.09
...      ...
230395 -0.01
230396 -0.01
230397 -0.04
230398  0.01
230399 -0.01

[230400 rows x 1 columns]
           0  1
0         88  N
1        190  S
2        368  N
3        461  S
4        635  N
...      ... ..
1704  229766  V
1705  229962  N
1706  230097  N
1707  230226  N
1708  230360  N

[1709 rows x 2 columns]
         0  1
0     1968  ~
1     2496  ~
2    70944  ~
3    71488  ~
4   100036  ~
5   100576  ~
6   110048  ~
7   110592  ~
8   160448  ~
9   160992  ~
10  173728  ~
11  174304  ~
12  176192  ~
13  176768  ~
14  183157  ~
15  183680  ~
16  190144  ~
17  190688  ~
18  191844  |
19  192032  ~
20  192576  ~
21  194922  |
22  209824  ~
23  210368  ~
24  210562  |
25  210784  ~
26  211140  |
27  212288  ~
28  220173  |
           0
0       0.03
1       0.01
2       0.01
3      -0.01
4       0.02
...      ...
230395 -0.44
230396 -0.47
230397 -0.47
230398 -0.43
230399 -0.42

[230400 rows x 1 columns]
           0  1
0        101  N
1        202  N
2        304  N
3        403  N
4        505  N
...      ... ..
2169  229902  N
2170  230011  N
2171  230120  N
2172  230232  N
2173  230344  N

[2174 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -2.255
1      -1.850
2      -1.220
3      -0.890
4      -0.755
...       ...
230395 -0.095
230396 -0.145
230397 -0.100
230398 -0.150
230399 -0.150

[230400 rows x 1 columns]
           0  1
0         16  N
1         99  N
2        182  N
3        264  N
4        346  N
...      ... ..
2601  229996  N
2602  230083  N
2603  230151  S
2604  230256  N
2605  230343  N

[2606 rows x 2 columns]
          0  1
0       464  |
1       967  |
2      1228  |
3      3278  |
4      3341  |
..      ... ..
168  220662  |
169  221210  |
170  222017  |
171  222197  |
172  227256  |

[173 rows x 2 columns]
                   0
0      -4.000000e-02
1      -7.000000e-02
2       2.000000e-02
3      -6.000000e-02
4       4.042199e-17
...              ...
230395 -1.900000e-01
230396 -2.021099e-16
230397 -7.000000e-02
230398 -7.000000e-02
230399 -1.200000e-01

[230400 rows x 1 columns]
           0  1
0         93  N
1        182  N
2        268  N
3        344  V
4        421  N
...      ... ..
2838  229981  V
2839  230084  N
2840  230178  N
2841  230227  S
2842  230326  N

[2843 rows x 2 columns]
        0  1
0   20541  |
1   37248  ~
2   37465  ~
3   38223  |
4   39648  ~
5   39712  ~
6   56581  |
7   69280  ~
8   69332  ~
9   70340  |
10  71244  |
11  71536  |
12  71563  ~
13  71840  ~
                   0
0      -6.300000e-01
1      -6.100000e-01
2      -6.000000e-01
3      -5.800000e-01
4      -5.100000e-01
...              ...
230395 -1.616879e-16
230396 -3.000000e-02
230397  1.000000e-02
230398  5.000000e-02
230399  1.000000e-02

[230400 rows x 1 columns]
           0  1
0         33  N
1        100  N
2        204  N
3        287  N
4        376  N
...      ... ..
2523  229956  N
2524  230057  N
2525  230156  N
2526  230254  N
2527  230305  V

[2528 rows x 2 columns]
Empty DataFrame
Columns: [0, 1]
Index: []
            0
0      -0.020
1      -0.030
2      -0.040
3      -0.040
4      -0.050
...       ...
230395  0.010
230396 -0.010
230397  0.010
230398  0.015
230399  0.005

[230400 rows x 1 columns]
           0  1
0         70  N
1        171  N
2        277  N
3        383  N
4        487  N
...      ... ..
2342  229934  N
2343  230040  N
2344  230136  N
2345  230195  S
2346  230321  N

[2347 rows x 2 columns]
         0  1
0     2809  |
1     2991  |
2     9967  |
3    19759  |
4    34124  |
..     ... ..
82  228598  ~
83  228655  ~
84  229704  ~
85  229961  ~
86  230240  ~

[87 rows x 2 columns]
                   0
0      -3.000000e-02
1       2.223209e-16
2      -9.000000e-02
3      -1.000000e-01
4      -4.000000e-02
...              ...
230395 -2.100000e-01
230396 -2.000000e-01
230397 -1.700000e-01
230398 -2.400000e-01
230399 -3.300000e-01

[230400 rows x 1 columns]

In [1]:
pip install word2number

Defaulting to user installation because normal site-packages is not writeable
Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py): started
  Building wheel for word2number (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5590 sha256=f220644c95712fae67b64be1b77b8b6b4984cc229e8fa26ba594847c7bb8b806
  Stored in directory: c:\users\ewunetie\appdata\local\pip\cache\wheels\29\85\cd\a78aeab138a03ac89a6ed4f8f00665d5ceb7ac0318c837a086
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (2.16.1)
Requirement already satisfied: tensorflow-intel==2.16.1 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow) (2.16.1)
Requirement already satisfied: libclang>=13.0.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (16.0.6)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.31.0)
Requirement already satisfied: h5py>=3.10.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (3.10.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (3.3.0)
Requirement already satisfied: ml-dtypes~=0.3.1 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.3.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.28.1)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.16.0)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.5.4)
Requirement already satisfied: keras>=3.0.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (3.0.5)
Requirement already satisfied: wrapt>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.14.1)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (22.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (24.3.7)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (4.25.3)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.2.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.4.0)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (65.6.3)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (4.4.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in c:\programdata\anaconda3\lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.23.5)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.1.0)
Requirement already satisfied: tensorboard<2.17,>=2.16 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.16.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.62.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.16.1->tensorflow) (0.38.4)
Requirement already satisfied: dm-tree in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (0.1.8)
Requirement already satisfied: rich in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (13.7.1)
Requirement already satisfied: namex in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (0.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (2024.2.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (1.26.14)
Requirement already satisfied: markdown>=2.6.8 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (2.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\programdata\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (2.1.1)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (2.17.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\ewunetie\appdata\roaming\python\python310\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.