In [16]:
import pandas as pd
import os

folder_path1 = 'C:/Users/Ewunetie/OneDrive - University of Gondar,/2022-2023 files/Courses/Project/CTRL/Chewing.csv'
folder_path2 = 'C:/Users/Ewunetie/OneDrive - University of Gondar,/2022-2023 files/Courses/Project/CTRL/Control.csv'
folder_path = 'C:/Users/Ewunetie/OneDrive - University of Gondar,/2022-2023 files/Courses/Project/CTRL'
df1 = pd.read_csv(folder_path1)
print(df1)
df2 = pd.read_csv(folder_path2)
print(df2)

dfs=pd.concat([df1, df2],axis=0)
df=pd.DataFrame(dfs)
print(df)

output_file_path = os.path.join(folder_path,"CTRL.csv")
df.to_csv(output_file_path, index=False)
df

       data_ID         0         1         2         3         4         5  \
0   A_01_06_06 -0.116201 -0.120952 -0.125470 -0.129755 -0.133807 -0.137628
1       A_01_1 -0.110777 -0.119968 -0.128788 -0.137072 -0.144673 -0.151463
2   A_01_17_07 -0.061985 -0.065903 -0.069614 -0.073117 -0.076413 -0.079501
3       A_01_2 -0.071215 -0.067523 -0.063781 -0.060007 -0.056219 -0.052437
4       A_01_3 -0.119150 -0.120002 -0.120831 -0.121598 -0.122282 -0.122872
..         ...       ...       ...       ...       ...       ...       ...
63      A_07_4 -0.042867 -0.040006 -0.037546 -0.035554 -0.034082 -0.033164
64      A_08_1  0.004036  0.017585  0.030874  0.043721  0.055952  0.067408
65      A_08_2 -0.087354 -0.086402 -0.085131 -0.083613 -0.081923 -0.080136
66      A_08_3 -0.007330 -0.009214 -0.011009 -0.012670 -0.014156 -0.015427
67      A_08_4 -0.014677 -0.015100 -0.015465 -0.015775 -0.016033 -0.016245

           6         7         8  ...     16373     16374     16375     16376  \
0  -0.141215 -0.144570 -0.147692  ... -0.140577 -0.142216 -0.143829 -0.145370
1  -0.157344 -0.162247 -0.166136  ... -0.112115 -0.114064 -0.115967 -0.117768
2  -0.082381 -0.085054 -0.087520  ... -0.042598 -0.041292 -0.040163 -0.039244
3  -0.048684 -0.044979 -0.041344  ... -0.048379 -0.048474 -0.048538 -0.048585
4  -0.123371 -0.123792 -0.124154  ... -0.415537 -0.394111 -0.370438 -0.345248
..       ...       ...       ...  ...       ...       ...       ...       ...
63 -0.032819 -0.033047 -0.033831  ... -0.026688 -0.026522 -0.026546 -0.026751
64  0.077946  0.087443  0.095800  ... -0.047111 -0.046589 -0.045931 -0.045112
65 -0.078319 -0.076532 -0.074827  ...  0.028132  0.026087  0.024014  0.021915
66 -0.016451 -0.017198 -0.017648  ... -0.041657 -0.040411 -0.038846 -0.036959
67 -0.016417 -0.016556 -0.016672  ... -0.061674 -0.064179 -0.066817 -0.069398

       16377     16378     16379     16380     16381     16382
0  -0.146797 -0.148074 -0.149168 -0.150053 -0.150706 -0.151112
1  -0.119419 -0.120877 -0.122106 -0.123078 -0.123769 -0.124165
2  -0.038572 -0.038178 -0.038093 -0.038341 -0.038940 -0.039903
3  -0.048634 -0.048705 -0.048821 -0.049004 -0.049278 -0.049663
4  -0.319237 -0.293054 -0.267288 -0.242461 -0.219016 -0.197320
..       ...       ...       ...       ...       ...       ...
63 -0.027120 -0.027628 -0.028243 -0.028929 -0.029646 -0.030352
64 -0.044118 -0.042945 -0.041599 -0.040095 -0.038454 -0.036707
65  0.019796  0.017655  0.015491  0.013303  0.011085  0.008833
66 -0.034756 -0.032254 -0.029476 -0.026456 -0.023231 -0.019847
67 -0.071704 -0.073488 -0.074484 -0.074406 -0.072959 -0.069847

[68 rows x 16384 columns]
       data_ID         0         1         2         3         4         5  \
0       C_01_1 -0.060757 -0.063852 -0.066923 -0.069933 -0.072853 -0.075654
1   C_01_17_07 -0.061985 -0.065903 -0.069614 -0.073117 -0.076413 -0.079501
2       C_01_2 -0.044535 -0.053890 -0.064269 -0.075458 -0.087177 -0.099078
3       C_01_3 -0.039560 -0.039457 -0.039018 -0.038201 -0.036967 -0.035283
4       C_02_1  0.327384  0.285837  0.242924  0.199535  0.156541  0.114777
..         ...       ...       ...       ...       ...       ...       ...
73  C_09_26_07  0.072516  0.084666  0.096211  0.107152  0.117489  0.127221
74      C_09_3 -0.093928 -0.093802 -0.093489 -0.092975 -0.092251 -0.091314
75      C_09_4 -0.008243 -0.007125 -0.005950 -0.004734 -0.003496 -0.002253
76      C_09_5  0.013856  0.013657  0.013206  0.012521  0.011624  0.010543
77  C_10_17_07 -0.110495 -0.107921 -0.105409 -0.102958 -0.100570 -0.098244

           6         7         8  ...     59990     59991     59992     59993  \
0  -0.078316 -0.080823 -0.083166  ... -0.014135 -0.013234 -0.012841 -0.013114
1  -0.082381 -0.085054 -0.087520  ...       NaN       NaN       NaN       NaN
2  -0.110753 -0.121738 -0.131520  ... -0.030722 -0.031974 -0.033193 -0.034370
3  -0.033126 -0.030480 -0.027340  ... -0.051976 -0.054064 -0.056045 -0.057891
4   0.075011  0.037931  0.004125  ... -0.048721 -0.050977 -0.051945 -0.051265
..       ...       ...       ...  ...       ...       ...       ...       ...
73  0.136348  0.144871  0.152790  ...       NaN       NaN       NaN       NaN
74 -0.090167 -0.088818 -0.087279  ... -0.012376 -0.012726 -0.012890 -0.012867
75 -0.001018  0.000197  0.001381  ...  0.002396  0.004371  0.006242  0.007971
76  0.009310  0.007958  0.006523  ...  0.126180  0.127804  0.129277  0.130603
77 -0.095979 -0.093777 -0.091637  ...       NaN       NaN       NaN       NaN

       59994     59995     59996     59997     59998     59999
0  -0.014210 -0.016275 -0.019439 -0.023803 -0.029434 -0.036355
1        NaN       NaN       NaN       NaN       NaN       NaN
2  -0.035491 -0.036534 -0.037477 -0.038288 -0.038932 -0.039370
3  -0.059570 -0.061045 -0.062277 -0.063224 -0.063841 -0.064086
4  -0.048576 -0.043522 -0.035769 -0.025011 -0.010987  0.006508
..       ...       ...       ...       ...       ...       ...
73       NaN       NaN       NaN       NaN       NaN       NaN
74 -0.012663 -0.012284 -0.011742 -0.011050 -0.010224 -0.009282
75  0.009523  0.010870  0.011986  0.012853  0.013457  0.013792
76  0.131788  0.132841  0.133772  0.134593  0.135319  0.135964
77       NaN       NaN       NaN       NaN       NaN       NaN

[78 rows x 60001 columns]
       data_ID         0         1         2         3         4         5  \
0   A_01_06_06 -0.116201 -0.120952 -0.125470 -0.129755 -0.133807 -0.137628
1       A_01_1 -0.110777 -0.119968 -0.128788 -0.137072 -0.144673 -0.151463
2   A_01_17_07 -0.061985 -0.065903 -0.069614 -0.073117 -0.076413 -0.079501
3       A_01_2 -0.071215 -0.067523 -0.063781 -0.060007 -0.056219 -0.052437
4       A_01_3 -0.119150 -0.120002 -0.120831 -0.121598 -0.122282 -0.122872
..         ...       ...       ...       ...       ...       ...       ...
73  C_09_26_07  0.072516  0.084666  0.096211  0.107152  0.117489  0.127221
74      C_09_3 -0.093928 -0.093802 -0.093489 -0.092975 -0.092251 -0.091314
75      C_09_4 -0.008243 -0.007125 -0.005950 -0.004734 -0.003496 -0.002253
76      C_09_5  0.013856  0.013657  0.013206  0.012521  0.011624  0.010543
77  C_10_17_07 -0.110495 -0.107921 -0.105409 -0.102958 -0.100570 -0.098244

           6         7         8  ...     59990     59991     59992     59993  \
0  -0.141215 -0.144570 -0.147692  ...       NaN       NaN       NaN       NaN
1  -0.157344 -0.162247 -0.166136  ...       NaN       NaN       NaN       NaN
2  -0.082381 -0.085054 -0.087520  ...       NaN       NaN       NaN       NaN
3  -0.048684 -0.044979 -0.041344  ...       NaN       NaN       NaN       NaN
4  -0.123371 -0.123792 -0.124154  ...       NaN       NaN       NaN       NaN
..       ...       ...       ...  ...       ...       ...       ...       ...
73  0.136348  0.144871  0.152790  ...       NaN       NaN       NaN       NaN
74 -0.090167 -0.088818 -0.087279  ... -0.012376 -0.012726 -0.012890 -0.012867
75 -0.001018  0.000197  0.001381  ...  0.002396  0.004371  0.006242  0.007971
76  0.009310  0.007958  0.006523  ...  0.126180  0.127804  0.129277  0.130603
77 -0.095979 -0.093777 -0.091637  ...       NaN       NaN       NaN       NaN

       59994     59995     59996     59997     59998     59999
0        NaN       NaN       NaN       NaN       NaN       NaN
1        NaN       NaN       NaN       NaN       NaN       NaN
2        NaN       NaN       NaN       NaN       NaN       NaN
3        NaN       NaN       NaN       NaN       NaN       NaN
4        NaN       NaN       NaN       NaN       NaN       NaN
..       ...       ...       ...       ...       ...       ...
73       NaN       NaN       NaN       NaN       NaN       NaN
74 -0.012663 -0.012284 -0.011742 -0.011050 -0.010224 -0.009282
75  0.009523  0.010870  0.011986  0.012853  0.013457  0.013792
76  0.131788  0.132841  0.133772  0.134593  0.135319  0.135964
77       NaN       NaN       NaN       NaN       NaN       NaN

[146 rows x 60001 columns]

,data_ID,0,1,2,3,4,5,6,7,8,...,59990,59991,59992,59993,59994,59995,59996,59997,59998,59999
0,A_01_06_06,-0.116201,-0.120952,-0.125470,-0.129755,-0.133807,-0.137628,-0.141215,-0.144570,-0.147692,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A_01_1,-0.110777,-0.119968,-0.128788,-0.137072,-0.144673,-0.151463,-0.157344,-0.162247,-0.166136,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A_01_17_07,-0.061985,-0.065903,-0.069614,-0.073117,-0.076413,-0.079501,-0.082381,-0.085054,-0.087520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A_01_2,-0.071215,-0.067523,-0.063781,-0.060007,-0.056219,-0.052437,-0.048684,-0.044979,-0.041344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A_01_3,-0.119150,-0.120002,-0.120831,-0.121598,-0.122282,-0.122872,-0.123371,-0.123792,-0.124154,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,C_09_26_07,0.072516,0.084666,0.096211,0.107152,0.117489,0.127221,0.136348,0.144871,0.152790,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,C_09_3,-0.093928,-0.093802,-0.093489,-0.092975,-0.092251,-0.091314,-0.090167,-0.088818,-0.087279,...,-0.012376,-0.012726,-0.012890,-0.012867,-0.012663,-0.012284,-0.011742,-0.011050,-0.010224,-0.009282
75,C_09_4,-0.008243,-0.007125,-0.005950,-0.004734,-0.003496,-0.002253,-0.001018,0.000197,0.001381,...,0.002396,0.004371,0.006242,0.007971,0.009523,0.010870,0.011986,0.012853,0.013457,0.013792
76,C_09_5,0.013856,0.013657,0.013206,0.012521,0.011624,0.010543,0.009310,0.007958,0.006523,...,0.126180,0.127804,0.129277,0.130603,0.131788,0.132841,0.133772,0.134593,0.135319,0.135964
77,C_10_17_07,-0.110495,-0.107921,-0.105409,-0.102958,-0.100570,-0.098244,-0.095979,-0.093777,-0.091637,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN